Repository cortexlabs/cortex, pull requests merged in 2020-07, with the labels that each got.

#1212 Fix POST response status codes
  docs/deployments/predictors.md
  pkg/workloads/cortex/serve/serve.py
Labels: bug

#1217 Fix OOM when reading files that don't fit into memory
  cli/cmd/deploy.go
  go.mod
  go.sum
  pkg/lib/files/errors.go
  pkg/lib/files/files.go
  pkg/lib/strings/stringify.go
Labels: bug, v0.19

#1181 Add more widgets to the CloudWatch Dashboard
  docs/guides/metrics.md
  pkg/lib/aws/cloudwatch.go
  pkg/lib/aws/errors.go
  pkg/operator/resources/syncapi/dashboard.go
Labels: enhancement, refactor, v0.19

#1213 Add traffic splitter API kind
  cli/cmd/get.go
  pkg/lib/k8s/virtual_service.go
  pkg/operator/endpoints/logs.go
  pkg/operator/resources/apisplitter/api.go
  pkg/operator/resources/apisplitter/k8s_specs.go
  pkg/operator/resources/apisplitter/status.go
  pkg/operator/resources/errors.go
  pkg/operator/resources/resources.go
  pkg/operator/resources/syncapi/k8s_specs.go
  pkg/operator/resources/validations.go
  pkg/operator/schema/schema.go
  pkg/types/spec/errors.go
  pkg/types/spec/validations.go
  pkg/types/userconfig/api.go
  pkg/types/userconfig/config_key.go
  pkg/types/userconfig/kind.go
Labels: enhancement
