Repository cortexlabs/cortex, pull requests merged in 2020-06, with the labels that each got.

#1101 Add '-y' option to conda install
  pkg/workloads/cortex/serve/run.sh
Labels: bug

#1104 Add shell instruction to serving Dockerfiles
  docs/deployments/system-packages.md
  images/onnx-predictor-cpu/Dockerfile
  images/onnx-predictor-gpu/Dockerfile
  images/python-predictor-cpu/Dockerfile
  images/python-predictor-gpu/Dockerfile
  images/tensorflow-predictor/Dockerfile
Labels: refactor

#1114 Add support for local Docker images
  pkg/lib/configreader/validators.go
  pkg/lib/docker/docker.go
  pkg/lib/docker/errors.go
  pkg/types/spec/validations.go
Labels: enhancement

#1154 Add .env to export environment variables
  cli/cmd/deploy.go
  docs/deployments/predictors.md
  pkg/workloads/cortex/serve/run.sh
Labels: enhancement

#1158 Move & rename replica parallelism fields
  cli/local/docker_spec.go
  docs/deployments/api-configuration.md
  docs/deployments/autoscaling.md
  docs/deployments/gpus.md
  docs/deployments/inferentia.md
  docs/deployments/parallelism.md
  docs/guides/batch-runner.md
  docs/summary.md
  examples/tensorflow/image-classifier-resnet50/README.md
  examples/tensorflow/image-classifier-resnet50/cortex_cpu.yaml
  examples/tensorflow/image-classifier-resnet50/cortex_gpu.yaml
  examples/tensorflow/image-classifier-resnet50/cortex_inf.yaml
  examples/tensorflow/image-classifier-resnet50/throughput_test.py
  examples/tensorflow/license-plate-reader/README.md
  examples/tensorflow/license-plate-reader/cortex_full.yaml
  images/tensorflow-serving-inf/run.sh
  images/tensorflow-serving-inf/template.conf
  pkg/consts/consts.go
  pkg/operator/operator/k8s_specs.go
  pkg/types/spec/errors.go
  pkg/types/spec/validations.go
  pkg/types/userconfig/api.go
  pkg/types/userconfig/config_key.go
  pkg/workloads/cortex/serve/serve.py
  pkg/workloads/cortex/serve/start_uvicorn.py
Labels: enhancement, refactor

#1141 Add troubleshooting page for TF sessions used in predict method
  docs/summary.md
  docs/troubleshooting/tf-session-in-predict.md
Labels: docs

#1166 Increase max number of processes per API replica
  pkg/types/spec/validations.go
Labels: performance

#1171 Use info log level when TF model is still being loaded
  pkg/workloads/cortex/lib/server/tensorflow.py
Labels: refactor

#1170 Improve Inferentia docs/examples
  docs/deployments/inferentia.md
  examples/pytorch/image-classifier-resnet50/README.md
  examples/pytorch/image-classifier-resnet50/generate_resnet50_models.ipynb
  examples/tensorflow/image-classifier-resnet50/README.md
  examples/tensorflow/image-classifier-resnet50/generate_resnet50_models.ipynb
Labels: docs

#1187 Fix dynamic axes for ONNX models
  pkg/workloads/cortex/lib/client/onnx.py
Labels: bug, v0.18

#1184 Remove unnecessary env var & reposition env var source
  cli/local/docker_spec.go
  pkg/operator/resources/syncapi/k8s_specs.go
  pkg/workloads/cortex/serve/run.sh
  pkg/workloads/cortex/serve/start_uvicorn.py
Labels: refactor
