Repository cortexlabs/cortex, pull requests merged in 2021-03, with the labels that each got.

#1912 Address AWS cluster up quota issues
  pkg/lib/aws/ec2.go
  pkg/lib/aws/errors.go
  pkg/lib/aws/servicequotas.go
  pkg/types/clusterconfig/cluster_config_aws.go
Labels: bug

#1905 Add granular pod metrics to the Grafana dashboards
  CONTRIBUTING.md
  build/images.sh
  charts/dashboards/batch.json
  charts/dashboards/realtime.json
  charts/templates/clusterconfig.yaml
  charts/templates/prometheus-kube-state-metrics.yaml
  charts/templates/prometheus-kubelet-exporter.yaml
  charts/templates/prometheus-monitoring.yaml
  charts/values.yaml
  cli/cmd/lib_cluster_config_aws.go
  dev/versions.md
  docs/clusters/aws/install.md
  docs/clusters/gcp/install.md
  images/prometheus-dcgm-exporter/Dockerfile
  images/prometheus-kube-state-metrics/Dockerfile
  manager/install.sh
  manager/manifests/grafana/grafana-dashboard-batch.yaml
  manager/manifests/grafana/grafana-dashboard-realtime.yaml
  manager/manifests/prometheus-dcgm-exporter.yaml
  manager/manifests/prometheus-kube-state-metrics.yaml
  manager/manifests/prometheus-kubelet-exporter.yaml
  manager/manifests/prometheus-monitoring.yaml.j2
  pkg/operator/operator/k8s.go
  pkg/operator/resources/validations.go
  pkg/types/clusterconfig/cluster_config_aws.go
  pkg/types/clusterconfig/cluster_config_gcp.go
  pkg/types/clusterconfig/config_key.go
Labels: enhancement

#1915 Prevent threads from being stuck in DynamicBatcher
  images/test/Dockerfile
  images/test/run.sh
  pkg/cortex/serve/cortex_internal.requirements.txt
  pkg/cortex/serve/cortex_internal/lib/api/batching.py
  pkg/cortex/serve/cortex_internal/lib/test/dynamic_batching_test.py
Labels: bug

#1945 Update cluster config arg in e2e tests and nightly build
  .circleci/config.yml
  test/e2e/e2e/cluster.py
Labels: bug

#1951 Add support for multi-instance-type clusters to AWS/GCP providers
  .circleci/config.yml
  cli/cmd/cluster.go
  cli/cmd/cluster_gcp.go
  cli/cmd/lib_cluster_config_aws.go
  manager/debug.sh
  manager/generate_eks.py
  manager/install.sh
  manager/manifests/cluster-autoscaler.yaml.j2
  manager/manifests/inferentia.yaml
  manager/manifests/nvidia_aws.yaml
  manager/manifests/nvidia_gcp.yaml
  manager/manifests/prometheus-dcgm-exporter.yaml
  manager/refresh.sh
  manager/requirements.txt
  pkg/lib/aws/cloudformation.go
  pkg/lib/aws/errors.go
  pkg/lib/aws/servicequotas.go
  pkg/lib/configreader/reader.go
  pkg/lib/configreader/string.go
  pkg/lib/hash/hash.go
  pkg/lib/maps/string.go
  pkg/lib/sets/strset/strset.go
  pkg/lib/telemetry/telemetry.go
  pkg/operator/config/config.go
  pkg/operator/endpoints/info.go
  pkg/operator/operator/cron.go
  pkg/operator/operator/k8s.go
  pkg/operator/operator/memory_capacity.go
  pkg/operator/resources/job/batchapi/k8s_specs.go
  pkg/operator/resources/job/taskapi/k8s_specs.go
  pkg/operator/resources/realtimeapi/k8s_specs.go
  pkg/operator/resources/validations.go
  pkg/operator/schema/schema.go
  pkg/types/clusterconfig/availability_zones.go
  pkg/types/clusterconfig/cluster_config.go
  pkg/types/clusterconfig/cluster_config_aws.go
  pkg/types/clusterconfig/cluster_config_gcp.go
  pkg/types/clusterconfig/config_key.go
  pkg/types/clusterconfig/errors.go
  pkg/types/clusterstate/clusterstate.go
  pkg/types/clusterstate/errors.go
  pkg/types/clusterstate/status.go
  test/apis/pytorch/image-classifier-resnet50/expectations.yaml
  test/e2e/README.md
  test/e2e/e2e/tests.py
  test/e2e/tests/aws/test_realtime.py
  test/e2e/tests/conftest.py
Labels: enhancement

#1968 Docs for multi-instance type clusters
  CONTRIBUTING.md
  docs/clusters/aws/install.md
  docs/clusters/aws/multi-instance-type.md
  docs/clusters/aws/spot.md
  docs/clusters/gcp/install.md
  docs/clusters/gcp/multi-instance-type.md
  docs/summary.md
  docs/workloads/realtime/troubleshooting.md
Labels: docs

#2002 Fix multi-model-classifier example for ONNX
  test/apis/onnx/multi-model-classifier/dependencies.sh
Labels: bug

#2015 Disallow the use of post_predict for grpc protocol
  pkg/cortex/serve/cortex_internal/lib/api/validations.py
Labels: ux

#2013 Fix downloader daemonsets
  manager/install.sh
  manager/manifests/image-downloader-cpu.yaml
  manager/manifests/image-downloader-gpu.yaml
  manager/manifests/image-downloader-inf.yaml
Labels: bug

#2024 Fix Grafana dashboards for Realtime/Batch API kinds
  manager/manifests/grafana/grafana-dashboard-batch.yaml
  manager/manifests/grafana/grafana-dashboard-realtime.yaml
Labels: bug

#2025 Remove transfer size limit for gRPC servers
  pkg/cortex/serve/start/server_grpc.py
Labels: performance
