Repository cortexlabs/cortex, pull requests merged in 2021-06, with the labels that each got.

#2209 Return from respondJSON func if an error occurs
  pkg/operator/endpoints/respond.go
Labels: bug

#2228 Remove latency checks for realtime load test & increase workload timeouts
  test/e2e/e2e/tests.py
  test/e2e/tests/conftest.py
Labels: tests

#2249 Fix grafana pod not starting (due to non-existent configmap)
  manager/install.sh
Labels: bug

#2250 Fix Inferentia deployments
  pkg/workloads/k8s.go
Labels: bug

#2255 Enlarge scope for stale stack discovery
  pkg/types/clusterconfig/cluster_config.go
Labels: enhancement

#2262 Add call to logger.Sync() on the test loggers and fix dequeuer test
  pkg/dequeuer/async_handler_test.go
  pkg/dequeuer/batch_handler_test.go
  pkg/dequeuer/dequeuer_test.go
  pkg/dequeuer/probes_test.go
  pkg/probe/handler_test.go
  pkg/probe/probe_test.go
Labels: tests

#2263 Remove task load test because of its unreliability
  test/e2e/e2e/tests.py
  test/e2e/e2e/utils.py
  test/e2e/tests/aws/test_load.py
  test/e2e/tests/conftest.py
Labels: tests

#2264 E2E cleanup
  test/e2e/e2e/tests.py
  test/e2e/e2e/utils.py
Labels: tests

#2272 Fix Circle CI build job
  .circleci/config.yml
  build/build-image.sh
  build/push-image.sh
  test/e2e/setup.py
Labels: bug

#2276 Fix Circle CI images being rebuilt on each step
  .circleci/config.yml
  Makefile
  build/push-image.sh
  build/push-images.sh
Labels: performance, tests

#2284 Attempt to fix 401 unauthorised error on image push
  .circleci/config.yml
  build/build-image.sh
  build/push-image.sh
Labels: bug

#2291 Fix E2E tests
  .circleci/config.yml
  test/apis/realtime/hello-world/cortex_cpu_arm64.yaml
  test/e2e/e2e/tests.py
  test/e2e/tests/aws/test_async.py
  test/e2e/tests/aws/test_autoscaling.py
  test/e2e/tests/aws/test_batch.py
  test/e2e/tests/aws/test_load.py
  test/e2e/tests/aws/test_long_running.py
  test/e2e/tests/aws/test_realtime.py
  test/e2e/tests/aws/test_task.py
  test/e2e/tests/conftest.py
Labels: bug, tests
